language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

sudo: false

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - ninja-build

before_install:
  - |
    if [ $TRAVIS_OS_NAME == osx ]; then
      brew update
      brew install ninja
      brew outdated cmake || brew upgrade cmake
    fi
  - |
    if [ $TRAVIS_OS_NAME == linux ]; then
      wget --no-check-certificate https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz
      tar -zxf cmake-3.6.2-Linux-x86_64.tar.gz
      export PATH=$PWD/cmake-3.6.2-Linux-x86_64/bin:$PATH
    fi

script:
  - cmake --version
  - ninja --version
  - mkdir build
  - cd build
  - cmake .. -G "Ninja"
  - ninja
  - ninja test
