#!/bin/sh
#                        Copyright (c) 1987 Bellcore
#                            All Rights Reserved
#       Permission is granted to copy or use this program, EXCEPT that it
#       may not be sold for profit, the copyright notice must be reproduced
#       on copies, and credit should be given to Bellcore where it is due.
#       BELLCORE MAKES NO WARRANTY AND ACCEPTS NO LIABILITY FOR THIS PROGRAM.

#	bury the window

BURY="8s"
ESC=""

if ismgrterm; then :
else
   echo "$0 only works on mgr terminals"
   exit 1
fi

echo -n "$ESC$BURY" &
