SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "The MGR Window System from Bellcore.")

SET(CPACK_PACKAGE_VENDOR "Workbench")
SET(CPACK_PACKAGE_CONTACT "Bruce Mitchener <bruce.mitchener@gmail.com>")

SET(CPACK_PACKAGE_VERSION_MAJOR "${MGR_VERSION_MAJOR}")
SET(CPACK_PACKAGE_VERSION_MINOR "${MGR_VERSION_MINOR}")
SET(CPACK_PACKAGE_VERSION_PATCH "${MGR_VERSION_PATCH}")

SET(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}_${MGR_VERSION}-${MGR_TARGET_PLATFORM}")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}_${MGR_VERSION}-sources")

SET(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/COPYRIGHT")
SET(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/README.rst")

SET(CPACK_SOURCE_IGNORE_FILES
    "/build.*"
    "/.git"
)

SET(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/waywardmonkeys/bellcore-mgr/")
SET(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
SET(CPACK_DEBIAN_PACKAGE_SECTION "libraries")

INCLUDE(CPack)
